name: Test Action

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: 23f1001645@ds.study.iitm.ac.in
        run: echo "Hello, world!"
